version: '3.8'

services:
  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: verdrehtewelt-wp
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      # Mount Theme direkt
      - ./theme/verdrehtewelt:/var/www/html/wp-content/themes/verdrehtewelt
      # WordPress Daten persistent
      - wordpress_data:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: verdrehtewelt-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'

  # phpMyAdmin (Optional, für DB-Management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: verdrehtewelt-pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
    restart: unless-stopped

volumes:
  wordpress_data:
  db_data:
